title: Caio Malaquias
logo: /images/bio-photo.jpg
description: " Berkeley Initiative for Transparency in the Social Sciences<br/> COS Ambassador<br/> Centre for Public Policy"
google_analytics:
theme: jekyll-theme-minimal
