title: Caio Malaquias
#logo: /images/bio-photo.jpg
description: "BITSS Catalyst<br/> COS Ambassador<br/> Centre for Public Policy<br/>
<br/> My research interests include Social & Political Behavior, Ideological and Affective Polarization,
Quantitative and Experimental Methods, and Research Transparency"
google_analytics:
theme: jekyll-theme-minimal
