title: Caio Malaquias
logo: /images/bio-photo.jpg
description: "Berkeley Initiative for Transparency in the Social Sciences Catalyst"
#show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
