title: Caio Malaquias
#logo: /images/bio-photo.jpg
description: "BITSS Catalyst<br/> COS Ambassador<br/> Centre for Public Policy<br/>
<br/> My research interests include Political Behavior, Affective Polarization,
Quantitative Methods, and Research Transparency"
google_analytics:
theme: jekyll-theme-minimal
