title: Caio Malaquias
logo: /images/bio-photo.jpg
description: [BITSS Catalyst](https://www.bitss.org/people/caio-malaquias/)
[COS Ambassador](https://cos.io/)
[Center for Public Policy](https://www3.ufpe.br/neppu/)
#show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
