title: Caio Malaquias
#logo: /images/bio-photo.jpg
description: "BITSS Catalyst<br/>
COS Ambassador<br/>
Centre for Public Policy <br/>

My research interests include Political Behaviour,<br/>
Affective Polarization, Quantitative Methods,<br/>
and Research Transparency"
google_analytics:
theme: jekyll-theme-minimal
